[package]
name = "rds-iam-rust-lambda"
version = "0.1.0"
edition = "2021"

[dependencies]
lambda_runtime = "0.12.0"
serde_json = "1.0.120"
aws-config = "1.0.1"
aws-credential-types = "1.0.1"
aws-sigv4 = "1.0.1"
url = "2.5.0"
tokio = { version = "1.25.0", features = ["full"] }
sqlx = { version = "0.7.4", features = ["tls-rustls", "mysql", "runtime-tokio"] }
